# Generated by Django 5.1.2 on 2025-02-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ism')),
                ('telegram_id', models.PositiveBigIntegerField(verbose_name='telegram id')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='tel raqam')),
                ('language', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=5)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='CategoryMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="o'zbekcha nomi")),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='ruscha nomi')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='inglizcha nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='UserMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='telegram id')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='foydalanuvchi ismi')),
                ('full_name', models.CharField(max_length=150, verbose_name="to'liq ismi")),
                ('language', models.CharField(max_length=10, verbose_name='til')),
                ('phone', models.CharField(max_length=20, verbose_name='tel raqam')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='ProductMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('price', models.PositiveIntegerField(verbose_name='narxi')),
                ('photo', models.ImageField(upload_to='media/products/', verbose_name='rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorymod', verbose_name='turi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='BasketMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveBigIntegerField(verbose_name='foydalanuvchi id')),
                ('category', models.PositiveIntegerField(verbose_name='kategoriya id')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmod', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
    ]
