# Generated by Django 5.1.2 on 2025-02-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ordermod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmod',
            name='language',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=5, verbose_name='til'),
        ),
        migrations.AlterField(
            model_name='adminmod',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='telefon raqam'),
        ),
    ]
