# Generated by Django 5.1.2 on 2025-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usermod_options_usermod_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='language',
            field=models.CharField(default=2, max_length=10, verbose_name='til'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermod',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='username'),
        ),
    ]
