# Generated by Django 5.1.2 on 2025-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_adminmod_language_alter_adminmod_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermod',
            name='overal_price',
            field=models.PositiveBigIntegerField(default=2, verbose_name='umumiy narxi'),
            preserve_default=False,
        ),
    ]
