# Generated by Django 5.1.2 on 2025-01-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usermod_language_alter_usermod_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.AlterField(
            model_name='usermod',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name="to'liq ism"),
        ),
        migrations.AlterField(
            model_name='usermod',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='foydalanuvchi ism'),
        ),
        migrations.CreateModel(
            name='ProductMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('price', models.PositiveIntegerField(verbose_name='narxi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name="ma'lumot")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorymod', verbose_name='turi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
