# Generated by Django 5.1.2 on 2025-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ordermod_overal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
    ]
