# Generated by Django 5.1.2 on 2025-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categorymod_alter_usermod_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymod',
            name='name',
        ),
        migrations.AddField(
            model_name='categorymod',
            name='name_en',
            field=models.CharField(default=2, max_length=100, verbose_name='inglizcha nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymod',
            name='name_ru',
            field=models.CharField(default=2, max_length=100, verbose_name='ruscha nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymod',
            name='name_uz',
            field=models.CharField(default=1, max_length=100, verbose_name="o'zbekcha nomi"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmod',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='rasmi'),
        ),
        migrations.AlterField(
            model_name='usermod',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name="to'liq ismi"),
        ),
        migrations.AlterField(
            model_name='usermod',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='foydalanuvchi ismi'),
        ),
    ]
