# Generated by Django 5.1.2 on 2025-02-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productmod_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmod',
            name='description',
        ),
    ]
