# Generated by Django 5.1.2 on 2025-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_categorymod_name_categorymod_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymod',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='inglizcha nomi'),
        ),
        migrations.AlterField(
            model_name='categorymod',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ruscha nomi'),
        ),
    ]
