# Generated by Django 5.1.2 on 2025-01-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_categorymod_name_en_alter_categorymod_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmod',
            name='description',
        ),
        migrations.CreateModel(
            name='BasketMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmod', verbose_name='mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usermod', verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
    ]
