# Generated by Django 5.1.2 on 2025-02-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_productmod_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.PositiveIntegerField(verbose_name='chegirma narxi')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='chegirma foizi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='sana')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
            },
        ),
    ]
