# Generated by Django 5.1.2 on 2025-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_productmod_description_basketmod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketmod',
            old_name='product',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='basketmod',
            name='category',
            field=models.CharField(default=2, max_length=100, verbose_name='turi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basketmod',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='soni'),
        ),
        migrations.AlterField(
            model_name='basketmod',
            name='user',
            field=models.PositiveBigIntegerField(verbose_name='foydalanuvchi id'),
        ),
    ]
