# Generated by Django 5.1.2 on 2025-01-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_product_basketmod_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketmod',
            old_name='product_name',
            new_name='product',
        ),
    ]
