# Generated by Django 5.1.2 on 2025-01-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_product_name_basketmod_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmod',
            name='category',
            field=models.PositiveIntegerField(max_length=100, verbose_name='turi'),
        ),
    ]
