# Generated by Django 5.1.2 on 2025-01-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_basketmod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmod',
            name='category',
            field=models.PositiveIntegerField(verbose_name='turi'),
        ),
    ]
