# Generated by Django 5.1.2 on 2025-01-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_usermod_phone_alter_basketmod_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ism')),
                ('telegram_id', models.PositiveBigIntegerField(verbose_name='telegram id')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='tel raqam')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
    ]
