# Generated by Django 5.1.2 on 2025-02-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_adminmod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmod',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admin'},
        ),
        migrations.AddField(
            model_name='adminmod',
            name='language',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=5),
        ),
    ]
