languages = {
    'uz': {
        'start': f"👋 Assalomu Alaykum {'full_name'}, buyurtma berishingiz mumkin!",
        'contact': '📞 Telefon raqamini yuborish',
        'contact_text': '📲 Telefon raqamingizni yuboring',
        
        'main': '📋 Asosiy menyu',
        'info': 'ℹ️ Ma\'lumotlar',
        'product_btn': '🛍 Mahsulotlar',
        'category_txt': 'Mahsulot turlari',
        'none_category': '📌 Bu kategoriyada vaxtincha mahsulotlar tugadi.',
        
        'my_basket': '🛒 Savat',
        'get_basket': 'Sizning savatingiz',
        'set_basket': '➕ Savatga qo\'shish',
        'none_basket': 'Savatingiz bo\'sh',
        'add_done': '✅ name savatchaga qo\'shildi!',
        'delete': '🗑 Savatdan o\'chirish',
        'delete_done': '✔️ Savatdan o\'chirildi!',
        
        'select_lang': '🇺🇿 Tilni tanlang',
        'set_lang': '🌍 Tilni o\'zgartirish',
        'lang_text': '🇺🇿 Hozirgi til O\'zbek tilidir',
        'lang_ru': '🇷🇺 Rus tiliga o\'zgartirish',
        'lang_en': '🇬🇧 Ingliz tiliga o\'zgartirish',
        'lang_changed': '☑️ Til o\'zgartirildi',
        
        'order': '✔️ Buyurtma berish',
        'order_done': '✔️ Buyurtmangiz yuborildi!',
        'order_all': 'Siz savatingizdagi barcha mahsulotlarga buyurtma berdingiz',
        'order_request': f"Sizning buyurtmangiz ko'rib chiqilmoqda...",
        'order_info': '🔘 Barchasini buyurtma qilasizmi yoki faqat shuni?',
        'one': 'faqat shuni',
        'all': 'barchasi',
        'order_yes': '✅ Buyurtmangiz qabul qilindi!',
        'order_no': '❌ Buyurtmangiz qabul qilinmadi.',
        
        'new_order': 'Yangi buyurtma',
        'yes': '✅ Tasdiqlash',
        'no': '❌ Bekor qilish',
        'done': 'Bajarildi',
        
        'previous_pg': '⬅️ Oldingi',
        'next_pg': 'Keyingi ➡️',
        'back': '🔙 Orqaga',
        'quantity': 'dona',
        'ban_cnt': 'kamaytira olmaysiz',
        
        'location_txt': '📍 Joylashuvingizni yuboring',
        'get_location': '📍 Joylashuvni yuborish',   
    },
    'ru': {
        'start': f"👋 Здравствуйте {'full_name'}, вы можете сделать заказ!",
        'contact': '📞 Отправить номер телефона',
        'contact_text': '📲 Отправьте свой номер телефона',
        
        'main': '📋 Главное меню',
        'info': 'ℹ️ Информация',
        'product_btn': '🛍 Продукты',
        'category_txt': 'Категории продуктов',
        'none_category': '📌 В данной категории ещё нет продуктов.',
        
        'my_basket': '🛒 Корзина',
        'get_basket': 'Ваша корзина',
        'set_basket': '➕ Добавить в корзину',
        'none_basket': 'Корзина пуста',
        'add_done': "✅ name добавлено в корзину!",
        'delete': '🗑 Удалить из корзины',
        'delete_done': '✔️ Удалено из корзины!',
        
        'select_lang': '🇷🇺 Выберите язык',
        'set_lang': '🌍 Изменить язык',
        'lang_text': '🇷🇺 Текуший язык русский',
        'lang_uz': '🇺🇿 Изменить язык на узбекский',
        'lang_en': '🇬🇧 Изменить язык на английский',
        'lang_changed': '☑️ Язык изменен',
        
        'order': '✔️ Оформить заказ',
        'order_info': '🔘 Заказать все или только это ?',
        'order_done': '✔️ Ваш заказ отправлен!',
        'order_all': 'Вы заказали все продукты из корзины',
        'order_request': f"Ваш заказ обрабатывается...",
        'one': 'только это',
        'all': 'все',
        'order_yes': '✅ Ваш заказ принят!',
        'order_no': '❌ Ваш заказ не принят!',
        
        'new_order': 'Новый заказ',
        'yes': '✅ Подтвердить',
        'no': '❌ Отказаться',
        'done': 'Выполнено',
        
        'previous_pg': '⬅️ Предыдущая',
        'next_pg': '➡️ Следующая',
        'back': '🔙 Назад',
        'quantity': 'штук',
        'ban_cnt': 'нельзя уменьшить',
        
        'location_txt': '📍 Отправьте свое местоположение',
        'get_location': '📍 Отправить местоположение',   
    },
    'en': {
        'start': f"👋 Hello {'full_name'}, you can place an order!",
        'contact': '📞 Send phone number',
        'contact_text': '📲 Send your phone number',
        
        'main': '📋 Main menu',
        'info': 'ℹ️ Information',
        'product_btn': '🛍 Products',
        'category_txt': 'Categories',
        'none_category': '📌 There are no products in this category.',
        
        'my_basket': '🛒 Basket',
        'get_basket': 'Your basket',
        'set_basket': '➕ Add to basket',
        'none_basket': 'Basket is empty',
        'add_done': "✅ name added to basket!",
        'delete': '🗑 Remove from basket',
        'delete_done': '✔️ Removed from basket!',
        
        'select_lang': '🇬🇧 Select a language',
        'set_lang': '🌍 Set language',
        'lang_text': '🇬🇧 Current language is English',
        'lang_uz': '🇺🇿 Change language to Uzbek',
        'lang_ru': '🇷🇺 Change language to Russian',
        'lang_changed': '☑️ Language changed',
        
        'order': '✔️ Make an order',
        'order_info': '🔘 Order all or just this one ?',
        'order_done': '✔️ Your order has been sent!',
        'order_all': 'You ordered all products from the basket',
        'order_request': f"Your order is being processed...",
        'one': 'this one',
        'all': 'all',
        'order_yes': "✅ Your order accepted!",
        'order_no': '❌ Your order rejected!',
        
        'new_order': 'New order',
        'yes': '✅ Confirm',
        'no': '❌ Decline',
        'done': 'Done',
        
        'previous_pg': '⬅️ Previous',
        'next_pg': '➡️ Next',
        'back': '🔙 Back',
        'quantity': 'pieces',
        'ban_cnt': 'cannot be reduced',
        
        'location_txt': '📍 Send your location',
        'get_location': '📍 Send location',
    }
}
