languages = {
    'uz': {
        'start': f"👋 Assalomu Alaykum {'full_name'}, buyurtma berishingiz mumkin!",
        'main': '📋 Asosiy menyu',
        'product_btn': '🛍 Mahsulotlar',
        'set_lang': '🌍 Tilni o\'zgartirish',
        'my_basket': '🛒 Savat',
        'info': 'ℹ️ Ma\'lumotlar',
        'lang_text': '🇺🇿 Hozirgi til O\'zbek tilidir',
        'lang_ru': '🇷🇺 Rus tiliga o\'zgartirish',
        'lang_en': '🇬🇧 Ingliz tiliga o\'zgartirish',
        'lang_changed': '☑️ Til o\'zgartirildi',
        'back': '🔙 Orqaga',
        'category_txt': 'Mahsulot turlari',
        'none_category': '📌 Bu kategoriyada vaxtincha mahsulotlar tugadi.',
        'set_basket': '➕ Savatga qo\'shish',
        'order': '',
        'previous_pg': '⬅️ Oldingi',
        'next_pg': 'Keyingi ➡️'
    },
    'ru': {
        'start': f"👋 Здравствуйте {'full_name'}, вы можете сделать заказ!",
        'main': '📋 Главное меню',
        'product_btn': '🛍 Продукты',
        'set_lang': '🌍 Изменить язык',
        'my_basket': '🛒 Корзина',
        'info': 'ℹ️ Информация',
        'lang_text': '🇷🇺 Текуший язык русский',
        'lang_uz': '🇺🇿 Изменить язык на узбекский',
        'lang_en': '🇬🇧 Изменить язык на английский',
        'lang_changed': '☑️ Язык изменен',
        'back': '🔙 Назад',
        'category_txt': 'Категории продуктов',
        'none_category': '📌 В данной категории ещё нет продуктов.',
        'set_basket': '➕ Добавить в корзину',
        'order': '',
        'previous_pg': '⬅️ Предыдущая',
        'next_pg': '➡️ Следующая',
    },
    'en': {
        'start': f"👋 Hello {'full_name'}, you can place an order!",
        'main': '📋 Main menu',
        'product_btn': '🛍 Products',
        'set_lang': '🌍 Set language',
        'my_basket': '🛒 Basket',
        'info': 'ℹ️ Information',
        'lang_text': '🇬🇧 Current language is English',
        'lang_uz': '🇺🇿 Change language to Uzbek',
        'lang_ru': '🇷🇺 Change language to Russian',
        'lang_changed': '☑️ Language changed',
        'back': '🔙 Back',
        'category_txt': 'Categories',
        'none_category': '📌 There are no products in this category.',
        'set_basket': '➕ Add to basket',
        'order': '',
        'previous_pg': '⬅️ Previous',
        'next_pg': '➡️ Next',
    }
}
